{"uuid": "bcd227f5-d199-430c-b755-8c7915b0c046", "children": ["3d9ccf24-9e05-4e4a-9b54-ed3e3c58f030"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 117\nCurrent browser version is 119.0.6045.125 with binary path C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe\nStacktrace:\n\tGetHandleVerifier [0x00007FF60B2578A2+54818]\n\t(No symbol) [0x00007FF60B1C6AD2]\n\t(No symbol) [0x00007FF60B07DA3B]\n\t(No symbol) [0x00007FF60B0B0972]\n\t(No symbol) [0x00007FF60B0AFDCE]\n\t(No symbol) [0x00007FF60B0AAA4B]\n\t(No symbol) [0x00007FF60B0A802E]\n\t(No symbol) [0x00007FF60B0E67FB]\n\t(No symbol) [0x00007FF60B0DE883]\n\t(No symbol) [0x00007FF60B0B3691]\n\t(No symbol) [0x00007FF60B0B48D4]\n\tGetHandleVerifier [0x00007FF60B5BB9A2+3610402]\n\tGetHandleVerifier [0x00007FF60B611870+3962352]\n\tGetHandleVerifier [0x00007FF60B609D5F+3930847]\n\tGetHandleVerifier [0x00007FF60B2F3656+693206]\n\t(No symbol) [0x00007FF60B1D1638]\n\t(No symbol) [0x00007FF60B1CD944]\n\t(No symbol) [0x00007FF60B1CDA72]\n\t(No symbol) [0x00007FF60B1BE123]\n\tBaseThreadInitThunk [0x00007FFBD04D257D+29]\n\tRtlUserThreadStart [0x00007FFBD162AA58+40]\n\n", "trace": "  File \"C:\\Users\\User\\PetFriendsProject\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\PetFriendsProject\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\PetFriendsProject\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\PetFriendsProject\\venv\\Lib\\site-packages\\pytest_selenium\\pytest_selenium.py\", line 200, in driver\n    for retry in Retrying(\n  File \"C:\\Users\\User\\PetFriendsProject\\venv\\Lib\\site-packages\\tenacity\\__init__.py\", line 347, in __iter__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\PetFriendsProject\\venv\\Lib\\site-packages\\tenacity\\__init__.py\", line 325, in iter\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\PetFriendsProject\\venv\\Lib\\site-packages\\tenacity\\__init__.py\", line 158, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\concurrent\\futures\\_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\concurrent\\futures\\_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"C:\\Users\\User\\PetFriendsProject\\venv\\Lib\\site-packages\\pytest_selenium\\pytest_selenium.py\", line 207, in driver\n    driver = driver_class(**driver_kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\PetFriendsProject\\venv\\Lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 84, in __init__\n    super().__init__(\n  File \"C:\\Users\\User\\PetFriendsProject\\venv\\Lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 104, in __init__\n    super().__init__(\n  File \"C:\\Users\\User\\PetFriendsProject\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 286, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"C:\\Users\\User\\PetFriendsProject\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 378, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\PetFriendsProject\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\User\\PetFriendsProject\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1700151223493, "stop": 1700151243996}], "start": 1700151223493, "stop": 1700151244144}